# Generated by Django 4.0.6 on 2022-07-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='statistics', max_length=30)),
                ('total_clicks', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('short_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('httpurl', models.URLField(null=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('index', models.IntegerField(default=0, null=True)),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
    ]
