# Generated by Django 4.0.6 on 2022-07-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Statistic',
        ),
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
