# Generated by Django 4.0.6 on 2022-07-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_statistics_statistic_rename_urls_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='name',
        ),
        migrations.AddField(
            model_name='statistic',
            name='short_id',
            field=models.SlugField(default=None, max_length=6),
        ),
    ]
