# Generated by Django 4.0.6 on 2022-07-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_statistic_name_statistic_short_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='total_clicks',
        ),
        migrations.AddField(
            model_name='statistic',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
